title = "ScopeGuardian CI Security Scan"

protected_branches = ["main", "master"]
path = "."

[kics]
platform = "Dockerfile"
exclude_queries = ["fd54f200-402c-4333-a5a4-36ef6709af2f"]

[grype]
ignore_states = "not-fixed,unknown,wont-fix"
transitive_libraries = false

[opengrep]
exclude = ["*_test.go", "docker-compose.yml"]
exclude_rule = ["go.lang.security.audit.dangerous-exec-command.dangerous-exec-command"]