title = "Scope-guardian configuration file"

protected_branches = ["main", "master"]
path = "./WebGoat"

[kics]
platform = "Dockerfile"

[grype]
ignore_states = "not-fixed,unknown,wont-fix"
transitive_libraries = false
