// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package defectdojo is a generated GoMock package.
package defectdojo

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDefectDojoService is a mock of DefectDojoService interface.
type MockDefectDojoService struct {
	ctrl     *gomock.Controller
	recorder *MockDefectDojoServiceMockRecorder
}

// MockDefectDojoServiceMockRecorder is the mock recorder for MockDefectDojoService.
type MockDefectDojoServiceMockRecorder struct {
	mock *MockDefectDojoService
}

// NewMockDefectDojoService creates a new mock instance.
func NewMockDefectDojoService(ctrl *gomock.Controller) *MockDefectDojoService {
	mock := &MockDefectDojoService{ctrl: ctrl}
	mock.recorder = &MockDefectDojoServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDefectDojoService) EXPECT() *MockDefectDojoServiceMockRecorder {
	return m.recorder
}

// CreateEngagement mocks base method.
func (m *MockDefectDojoService) CreateEngagement(projectName string, branch string, productId int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEngagement", projectName, branch, productId)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEngagement indicates an expected call of CreateEngagement.
func (mr *MockDefectDojoServiceMockRecorder) CreateEngagement(projectName, branch, productId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEngagement", reflect.TypeOf((*MockDefectDojoService)(nil).CreateEngagement), projectName, branch, productId)
}

// GetEngagements mocks base method.
func (m *MockDefectDojoService) GetEngagements(productId uint, offset int, limit int, engagements []Engagement) ([]Engagement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEngagements", productId, offset, limit, engagements)
	ret0, _ := ret[0].([]Engagement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEngagements indicates an expected call of GetEngagements.
func (mr *MockDefectDojoServiceMockRecorder) GetEngagements(productId, offset, limit, engagements interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEngagements", reflect.TypeOf((*MockDefectDojoService)(nil).GetEngagements), productId, offset, limit, engagements)
}

// GetProductByName mocks base method.
func (m *MockDefectDojoService) GetProductByName(productName string) (Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductByName", productName)
	ret0, _ := ret[0].(Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductByName indicates an expected call of GetProductByName.
func (mr *MockDefectDojoServiceMockRecorder) GetProductByName(productName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductByName", reflect.TypeOf((*MockDefectDojoService)(nil).GetProductByName), productName)
}

// ImportScan mocks base method.
func (m *MockDefectDojoService) ImportScan(payload ScanPayload, filename string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportScan", payload, filename)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImportScan indicates an expected call of ImportScan.
func (mr *MockDefectDojoServiceMockRecorder) ImportScan(payload, filename interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportScan", reflect.TypeOf((*MockDefectDojoService)(nil).ImportScan), payload, filename)
}

// SetAccessToken mocks base method.
func (m *MockDefectDojoService) SetAccessToken(token string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAccessToken", token)
}

// SetAccessToken indicates an expected call of SetAccessToken.
func (mr *MockDefectDojoServiceMockRecorder) SetAccessToken(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAccessToken", reflect.TypeOf((*MockDefectDojoService)(nil).SetAccessToken), token)
}

// SetURL mocks base method.
func (m *MockDefectDojoService) SetURL(url string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetURL", url)
}

// SetURL indicates an expected call of SetURL.
func (mr *MockDefectDojoServiceMockRecorder) SetURL(url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetURL", reflect.TypeOf((*MockDefectDojoService)(nil).SetURL), url)
}

// UpdateEngagementEndDate mocks base method.
func (m *MockDefectDojoService) UpdateEngagementEndDate(engagementId, productId int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEngagementEndDate", engagementId, productId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEngagementEndDate indicates an expected call of UpdateEngagementEndDate.
func (mr *MockDefectDojoServiceMockRecorder) UpdateEngagementEndDate(engagementId, productId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEngagementEndDate", reflect.TypeOf((*MockDefectDojoService)(nil).UpdateEngagementEndDate), engagementId, productId)
}
